name: RememVR Daily Check
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 23 * * *"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: ğŸ“¦ [Setup] Checkout
        uses: actions/checkout@v4

      - name: ğŸ“¦ [Setup] Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸ“¦ [Setup] Setup .env
        run: |
          # copy all secrets from github secrets, and create .env file
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: ğŸ“¦ [Setup] Install Dependencies
        run: npm install

      - name: âš™ï¸ [Test] Run Test
        run: npm run test
